site_name: "Cours en tout genre"
site_url: https://caranouga.github.io/cours/
nav:
 - 'accueil' : 'index.md'


theme:
  name: material
  custom_dir: my_theme_customizations/
  language: fr
  icon:
    logo: material/lightbulb-on-10
    repo : fontawesome/brands/github
    admonition:
      note: fontawesome/solid/pen-to-square


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide
    - content.code.annotate 
    - content.code.copy

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  # - meta
  - tables
  - abbr
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  # - pymdownx.highlight:
  #     linenums: None
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem:
      smart_enable: all
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - md_in_html


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      fallback_to_build_date: true
      locale: fr
  - awesome-pages:
      collapse_single_pages: false
  - macros
  

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:gilles.lassus@ac-bordeaux.fr
      name: Écrire à l'auteur

    - icon: fontawesome/brands/github
      link: https://github.com/glassus/premiere_nsi
      name: Dépôt git

    - icon: fontawesome/solid/school
      link: https://lyceemauriac.fr
      name: Lycée François Mauriac - Bordeaux

extra_javascript:
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js

extra_css:
  - stylesheets/extra.css




copyright:  CC BY-NC-SA / Caranouga

repo_url: https://github.com/caranouga/cours

repo_name: caranouga/cours
